### ISSUE TITLE
Is dataset available? 

### ISSUE THREAD

**Issue by dsellanes** [WorkInTheDark/FairytaleQA_QAG_System#1]
In both the paper & the repo is mentioned that the dataset is available at: 

https://github.com/uci-soe/FairytaleQAData

However, this link doesn't work. 

<img width="857" alt="image" src="https://user-images.githubusercontent.com/25889480/190020389-32ebbf95-e6c7-4d0e-8ad1-682dbca92796.png">

I was wondering if there's any way I can get access to the data. Or if is this some issue that is going to get fixed. 

Thank you!

**Comment by WorkInTheDark** [comment]
yes, the original repo is not available now. We've set up a backup repo for the dataset here: https://github.com/WorkInTheDark/FairytaleQA_Dataset  

also updated the link in readmes, thanks for raising the issue.

**Comment by dsellanes** [comment]
Amazing! 

thank you for the quick response!
